{% set version = '0.10-45' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tseries
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tseries_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tseries/tseries_{{ version }}.tar.gz
  sha256: c08eb1682286e9f2e0633976e4fad6c224f760f5e70b55006dbbfd5f207d4193

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tseries')"           # [not win]
    - "\"%R%\" -e \"library('tseries')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=tseries
  license: GPL-2
  summary: Time series analysis and computational finance.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tseries
# Version: 0.10-45
# Title: Time Series Analysis and Computational Finance
# Authors@R: c(person("Adrian", "Trapletti", role = "aut", email = "adrian@trapletti.org"), person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org"), person("Blake", "LeBaron", role = "ctb", comment = "BDS test code"))
# Description: Time series analysis and computational finance.
# Depends: R (>= 2.10.0)
# Imports: graphics, stats, utils, quadprog, zoo, quantmod (>= 0.4-9)
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2018-06-04 09:49:39 UTC; hornik
# Author: Adrian Trapletti [aut], Kurt Hornik [aut, cre], Blake LeBaron [ctb] (BDS test code)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-06-04 10:36:40 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
