travis:
  secure:
    BINSTAR_TOKEN: VNhvW09r7Sy2n5mj1MlNdM0GpBwhz1WMVwR6gF/2rmSVj8FwYVjCv/9funy8Xl9fTqb6OA7XY6p4n6REYXYlDkKAH3eZ2/GyB2pIyFDjx0Lth7Wu8bEfR+fyj2LCaQh7RrAR1BcDXIwSMWL+jS3IaLpYn6S3LHdqAaF9V1fdCv2Siv0pOA5wNhyzhM+/YP7DhhJB4/yYRK9I1Qnt158H+S0WpiW1hRZwO2kl9puaJyEb3HTMum/v4hZDenqrGUYJ8fNFv0XWYOUXUaKdXe1F+Y/Ony+onk8L45t4wiWEzHyqjVrcZlaSuzx852hqNwYvkRmliBO4iXUfpBQT3xuA5yWoen2yKFbcp10QP1qYFh6duNFvLF+gQ5szwtGnYGw/j1hpwD265afp3dIS/rJJmfNKXqEeUAkqbpmdt+ct0HUXfAKvn3RgOdHeP58Vm44PodgpiycHRtG13Z2QGQrOQAD5l5/bGVLii+6JARfyn6Sz6IhI9p4wFmw7oIxE+TtKTON3D5OgR2Fjq/TxMgI3h6/9X8lkjqSDkiOgMxv5gve0GdktgzaTqYxhhkY7Cj3WvOLREhJL8QoEw2cnsKJC9l7MWf5G/nJxS+R56pkIc57NAUnzQmreor2K4f1HU7LT+mGfPul4OunZkLh0meJl4H9H44CDXsaFub3tr6OTooQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
