travis:
  secure:
    BINSTAR_TOKEN: XivoIUgPgd1oLQ0YjD9pzkXGAPIa97fdVpvVUL/t9KdA5YTeK6m8/BmXNeb0fnwqfeBVUCfb/AxWZMhoSfJzIEmE5AKPZTeUIwDvopNehiCXf3Oec1yMxTaqVlO+nqQ9IF+QxjTHahaEdzkqGlYNT9PKGCNBvtDhcS4Y3lEtMLmcMV+akkN3dWK5/zz7JSeA9zsYSqVgb9jrraGOODj94NSVREhUIgOZ1tUgUvOM8TQPUXg/FyV3iDIxcN2jSinF6ldxMzxbxP+y8L7FxCQwjF08b0WsW0on1/RgNEdst4bMf7c5/DfwrpbAoMlvmKUmeOukQ+nIXhvE8NWwljJLTu4hUBN8cSCTK79BrdkRkvqvY/51bPR1qXWLLUF+0Q+f3H/5HhD4gyqXsaVQ3GIACQS8AzRzk3IoTWgonDBflrUz+xK1At2eTo10iF9vXFdoQv2JuyPSjgCoYb174hJXUDH4ORUOKiMZeKzu585aD2vC97oajFyMBVay71QIpmJeNsCRjvYtwIBKBdaN0totRydr7MS+HxyDvl53NyhF48EYARyw6fNtLdZqG6PAJQNmh6vWo4bCusWstDo79PL0YoJzjCuN73is84bYJFyg26Y2sJGzKF8yof4ArXArVEt6iSBKAoooPHAZcYGy0wt9SNEcqAGnj1/9euXepM9xrms=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
